on: [pull_request]

name: validate-OpenAPI-changes
jobs:
  detect-breaking-changes: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out HEAD revision
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: head
    - name: Check out BASE revision
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: base   
    - name: Run OpenAPI Diff (from HEAD revision)
      uses: docker://openapitools/openapi-diff:latest 
      with:
        args: head/schemas/api.github.com.yaml base/schemas/api.github.com.yaml --html results.txt
    - name: Create results comment for the PR
      id: comment
      uses: pCYSl5EDgo/cat@master
      with:
       path: results.txt
    - name: Add results comment on PR 
      uses: actions/github-script@47f7cf65b5ced0830a325f705cad64f2f58dddf7
      if: steps.comment.outputs.text != null && github.event_name == 'pull_request'
      env:
        COMMENT: ${{ steps.comment.outputs.text }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: process.env.COMMENT });

