on: [pull_request]

name: openapi-diff
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out HEAD revision
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: head
    - name: Check out BASE revision
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: base   
    - name: What OS
      run: uname -a
    - name: LS
      run: ls
    - name: Run OpenAPI Diff (from HEAD revision)
      uses: docker://openapitools/openapi-diff:latest 
      with:
        args: head/schemas/api.github.com.yaml base/schemas/api.github.com.yaml

