on: [pull_request]

name: openapi-diff

jobs:
  job-name:
    runs-on: ubuntu-latest
    container:
      image: openapitools/openapi-diff
    steps:
      - name: Check out HEAD revision
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: head
      - name: Check out BASE revision
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: base   
      - name: Run OpenAPI Diff (from HEAD revision)
        run: docker build -t local-openapi-diff .
        # run: openapitools/openapi-diff head/api.github.com.yaml base/api.github.com.yaml

