on: [pull_request]

name: validate-OpenAPI-changes
jobs:
  detect-breaking-changes: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out HEAD revision
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: head
    - name: Check out BASE revision
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: base 
    - name: Run OpenAPI Diff (from HEAD revision)
      run: > 
        docker run --rm -t 
        -v $(pwd)/head/schemas:/head:ro 
        -v $(pwd)/base/schemas:/base:ro 
        -v $(pwd):/results:rw 
        openapitools/openapi-diff:2.0.0-beta.9 /head/api.github.com.yaml /base/api.github.com.yaml  
        --text /results/results.txt
    - name: Format results comment for the PR
      id: comment
      run: echo ::set-output name=results::$(cat results.txt | while read i; do echo $i\<br\>; done)
    - name: Add results comment on PR 
      uses: actions/github-script@v4.0.2
      if: steps.comment.outputs.results != null && github.event_name == 'pull_request'
      env:
        COMMENT: ${{ steps.comment.outputs.results }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          console.log(JSON.stringify(context));
          github.issues.createComment({ issue_number, owner, repo, body: process.env.COMMENT });
    - name: Run OpenAPI Diff (get state)
      # This is fragile - the alternative is to run validation again with --state and validate that result
      if: ${{ !env.ACT }} && "contains(steps.comment.outputs.results, 'API changes broke backward compatibility')"
      run: exit 1
  

