on: [pull_request]

name: openapi-diff

jobs:
  job-name:
    runs-on: ubuntu-latest
    container:
      image: openapitools/openapi-diff
    steps:
     - name: Log the node version
       run: |
         node -v
         cat /etc/os-release
